### ISSUE TITLE
Support for commitlint YAML file

### ISSUE THREAD

**Issue by galak75** [lppedd/idea-conventional-commit-commitlint#5]
Hi 

First of all, thank you for the amazing work on this plugin.

Would it be possible to add support for yaml file format ? Or is it already supported ?

**Comment by lppedd** [comment]
@galak75 hi! No, currently only JSON is supported, but YAML shouldn't be difficult to add.
Could you point me to an example of YAML config? So I can tell you what I can support and what I cannot.

**Comment by galak75** [comment]
I will look for a reference documentation, but here is a small example:

```yaml
extends:
  - '@commitlint/config-conventional'
rules:
  header-max-length: [1, 'always', 72]
  type-enum:
  - 2
  - always
  - - ci
    - feat
    - fix
    - docs
    - style
    - refactor
    - perf
    - test
    - revert
help: |
  **Possible types**:
  `ci`:       Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
  `feat`:     Adds a new feature.
  `fix`:      Solves a bug.
  `docs`:     Adds or alters documentation.
  `style`:    Improves formatting, white-space.
  `refactor`: Rewrites code without feature, performance or bug changes.
  `perf`:     Improves performance.
  `test`:     Adds or modifies tests.
  `revert`:   Changes that reverting other changes
```
